services:
  migration:
    container_name: pokemon-migration
    build: .
    command: python migrate.py
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - pokemon-network

  scraper:
    container_name: pokemon-scraper
    build: .
    command: python scraper.py
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      migration:
        condition: service_completed_successfully
    networks:
      - pokemon-network

  web:
    container_name: pokemon-api
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      scraper:
        condition: service_completed_successfully
    networks:
      - pokemon-network

networks:
  pokemon-network:
    driver: bridge
